### ISSUE TITLE
Windows Domain Controller Fails to build

### ISSUE THREAD

**Issue by s-koniarz** [splunk/attack_range#248]
When running terraform or packer fails to build the windows domain controller using the default config.  

#### us-east-2
```
python attack_range.py -m packer -a build_amis
starting program loaded for B1 battle droid
          ||/__'`.
          |//()'-.:
          |-.||
          |o(o)
          |||\\  .==._
          |||(o)==::'
           `|T  ""
            ()
            |\
            ||\
            ()()
            ||//
            |//
           .'=`=.
attack_range is using config at path attack_range.conf
2020-04-09 09:18:21,360 - INFO - attack_range - INIT - attack_range v1
2020-04-09 09:18:21,373 - INFO - attack_range - [action] > build AMIs
2020-04-09 09:18:21,374 - INFO - attack_range - Generate new Packer AMI packer-splunk-server-attack-range-key-pair. This can take some time.
2020-04-09 09:31:21,231 - INFO - attack_range - successfully generated Packer AMI packer-splunk-server-attack-range-key-pair
2020-04-09 09:31:21,231 - INFO - attack_range - Generate new Packer AMI packer-windows-domain-controller-attack-range-key-pair. This can take some time.
2020-04-09 09:31:22,272 - ERROR - attack_range - ERROR: b'1586439081,,ui,say,==> amazon-ebs: Force Deregister flag found%!(PACKER_COMMA) skipping prevalidating AMI Name\n1586439081,,ui,error,==> amazon-ebs: No AMI was found matching filters: {\\n==> amazon-ebs:   Filters: [{\\n==> amazon-ebs:       Name: "name"%!(PACKER_COMMA)\\n==> amazon-ebs:       Values: ["Windows_Server_2016"]\\n==> amazon-ebs:     }%!(PACKER_COMMA){\\n==> amazon-ebs:       Name: "root-device-type"%!(PACKER_COMMA)\\n==> amazon-ebs:       Values: ["ebs"]\\n==> amazon-ebs:     }%!(PACKER_COMMA){\\n==> amazon-ebs:       Name: "virtualization-type"%!(PACKER_COMMA)\\n==> amazon-ebs:       Values: ["hvm"]\\n==> amazon-ebs:     }]%!(PACKER_COMMA)\\n==> amazon-ebs:   Owners: ["801119661308"]\\n==> amazon-ebs: }\n1586439081,,ui,error,Build \'amazon-ebs\' errored: No AMI was found matching filters: {\\n  Filters: [{\\n      Name: "name"%!(PACKER_COMMA)\\n      Values: ["Windows_Server_2016"]\\n    }%!(PACKER_COMMA){\\n      Name: "root-device-type"%!(PACKER_COMMA)\\n      Values: ["ebs"]\\n    }%!(PACKER_COMMA){\\n      Name: "virtualization-type"%!(PACKER_COMMA)\\n      Values: ["hvm"]\\n    }]%!(PACKER_COMMA)\\n  Owners: ["801119661308"]\\n}\n1586439081,,error-count,1\n1586439081,,ui,error,\\n==> Some builds didn\'t complete successfully and had errors:\n1586439081,amazon-ebs,error,No AMI was found matching filters: {\\n  Filters: [{\\n      Name: "name"%!(PACKER_COMMA)\\n      Values: ["Windows_Server_2016"]\\n    }%!(PACKER_COMMA){\\n      Name: "root-device-type"%!(PACKER_COMMA)\\n      Values: ["ebs"]\\n    }%!(PACKER_COMMA){\\n      Name: "virtualization-type"%!(PACKER_COMMA)\\n      Values: ["hvm"]\\n    }]%!(PACKER_COMMA)\\n  Owners: ["801119661308"]\\n}\n1586439081,,ui,error,--> amazon-ebs: No AMI was found matching filters: {\\n  Filters: [{\\n      Name: "name"%!(PACKER_COMMA)\\n      Values: ["Windows_Server_2016"]\\n    }%!(PACKER_COMMA){\\n      Name: "root-device-type"%!(PACKER_COMMA)\\n      Values: ["ebs"]\\n    }%!(PACKER_COMMA){\\n      Name: "virtualization-type"%!(PACKER_COMMA)\\n      Values: ["hvm"]\\n    }]%!(PACKER_COMMA)\\n  Owners: ["801119661308"]\\n}\n1586439081,,ui,say,\\n==> Builds finished but no artifacts were created.\n'
Traceback (most recent call last):
  File "attack_range.py", line 132, in <module>
    controller.build_amis()
  File "/home/range/attack_range/modules/PackerController.py", line 38, in build_amis
    sys.exit(1)
NameError: name 'sys' is not defined
```
#### us-west-2
```
python attack_range.py -m packer -a build_amis

starting program loaded for B1 battle droid
          ||/__'`.
          |//()'-.:
          |-.||
          |o(o)
          |||\\  .==._
          |||(o)==::'
           `|T  ""
            ()
            |\
            ||\
            ()()
            ||//
            |//
           .'=`=.

attack_range is using config at path attack_range.conf
2020-04-09 10:20:11,398 - INFO - attack_range - INIT - attack_range v1
2020-04-09 10:20:11,416 - INFO - attack_range - [action] > build AMIs

2020-04-09 10:20:11,417 - INFO - attack_range - Generate new Packer AMI packer-splunk-server-attack-range-key-pair. This can take some time.
2020-04-09 10:33:43,990 - INFO - attack_range - successfully generated Packer AMI packer-splunk-server-attack-range-key-pair
2020-04-09 10:33:43,991 - INFO - attack_range - Generate new Packer AMI packer-windows-domain-controller-attack-range-key-pair. This can take some time.
2020-04-09 10:33:45,429 - ERROR - attack_range - ERROR: b'1586442824,,ui,say,==> amazon-ebs: Force Deregister flag found%!(PACKER_COMMA) skipping prevalidating AMI Name\n1586442825,,ui,error,==> amazon-ebs: No AMI was found matching filters: {\\n==> amazon-ebs:   Filters: [{\\n==> amazon-ebs:       Name: "name"%!(PACKER_COMMA)\\n==> amazon-ebs:       Values: ["Windows_Server-2016-English-Full-Base-2019.12.16"]\\n==> amazon-ebs:     }%!(PACKER_COMMA){\\n==> amazon-ebs:       Name: "root-device-type"%!(PACKER_COMMA)\\n==> amazon-ebs:       Values: ["ebs"]\\n==> amazon-ebs:     }%!(PACKER_COMMA){\\n==> amazon-ebs:       Name: "virtualization-type"%!(PACKER_COMMA)\\n==> amazon-ebs:       Values: ["hvm"]\\n==> amazon-ebs:     }]%!(PACKER_COMMA)\\n==> amazon-ebs:   Owners: ["801119661308"]\\n==> amazon-ebs: }\n1586442825,,ui,error,Build \'amazon-ebs\' errored: No AMI was found matching filters: {\\n  Filters: [{\\n      Name: "name"%!(PACKER_COMMA)\\n      Values: ["Windows_Server-2016-English-Full-Base-2019.12.16"]\\n    }%!(PACKER_COMMA){\\n      Name: "root-device-type"%!(PACKER_COMMA)\\n      Values: ["ebs"]\\n    }%!(PACKER_COMMA){\\n      Name: "virtualization-type"%!(PACKER_COMMA)\\n      Values: ["hvm"]\\n    }]%!(PACKER_COMMA)\\n  Owners: ["801119661308"]\\n}\n1586442825,,error-count,1\n1586442825,,ui,error,\\n==> Some builds didn\'t complete successfully and had errors:\n1586442825,amazon-ebs,error,No AMI was found matching filters: {\\n  Filters: [{\\n      Name: "name"%!(PACKER_COMMA)\\n      Values: ["Windows_Server-2016-English-Full-Base-2019.12.16"]\\n    }%!(PACKER_COMMA){\\n      Name: "root-device-type"%!(PACKER_COMMA)\\n      Values: ["ebs"]\\n    }%!(PACKER_COMMA){\\n      Name: "virtualization-type"%!(PACKER_COMMA)\\n      Values: ["hvm"]\\n    }]%!(PACKER_COMMA)\\n  Owners: ["801119661308"]\\n}\n1586442825,,ui,error,--> amazon-ebs: No AMI was found matching filters: {\\n  Filters: [{\\n      Name: "name"%!(PACKER_COMMA)\\n      Values: ["Windows_Server-2016-English-Full-Base-2019.12.16"]\\n    }%!(PACKER_COMMA){\\n      Name: "root-device-type"%!(PACKER_COMMA)\\n      Values: ["ebs"]\\n    }%!(PACKER_COMMA){\\n      Name: "virtualization-type"%!(PACKER_COMMA)\\n      Values: ["hvm"]\\n    }]%!(PACKER_COMMA)\\n  Owners: ["801119661308"]\\n}\n1586442825,,ui,say,\\n==> Builds finished but no artifacts were created.\n'
Traceback (most recent call last):
  File "attack_range.py", line 132, in <module>
    controller.build_amis()
  File "/home/range/attack_range/modules/PackerController.py", line 38, in build_amis
    sys.exit(1)
NameError: name 'sys' is not defined
```

### Terraform
```
python attack_range.py -m terraform -a build
2020-04-08 20:18:37,855 - INFO - attack_range - INIT - attack_range v1
2020-04-08 20:18:37,855 - INFO - attack_range - [action] > build
module.splunk-server.data.aws_ami.latest-ubuntu[0]: Refreshing state...
module.kali_machine.data.aws_ami.latest-kali-linux: Refreshing state...
module.windows-domain-controller.data.aws_ami.latest-windows-server-2016[0]: Refreshing state...
Error: Your query returned no results. Please change your search criteria and try again.
  on modules/windows-domain-controller/resources.tf line 2, in data "aws_ami" "latest-windows-server-2016":
   2: data "aws_ami" "latest-windows-server-2016" {
```

**Comment by P4T12ICK** [comment]
Thank you very much for the feedback. I think I found the issue. Can you try to use the following values in attack_range.conf 
...
windows_domain_controller_os = Windows_Server-2016-English-Full-Base-*
...
windows_server_os = Windows_Server-2016-English-Full-Base-*
...

I'm testing in parallel.

**Comment by s-koniarz** [comment]
Testing now as well

**Comment by P4T12ICK** [comment]
It worked for me. If it also worked for youthen I will turn it into a bug fix branch and create a pull request.

**Comment by s-koniarz** [comment]
It worked for me as well.

**Comment by P4T12ICK** [comment]
Thank you for your feedback. I will turn this into a Pull Request.
