### ISSUE TITLE
No such file or directory: 'terraform': 'terraform' when building

### ISSUE THREAD

**Issue by fierytermite** [splunk/attack_range#342]
Hi! I've been trying to build attack_range in both an Ubuntu 18 and an Ubuntu 20 machine, and I'm getting this error while building.

```
starting program loaded for B1 battle droid
          ||/__'`.
          |//()'-.:
          |-.||
          |o(o)
          |||\\  .==._
          |||(o)==::'
           `|T  ""
            ()
            |\
            ||\
            ()()
            ||//
            |//
           .'=`=.
    
attack_range is using config at path attack_range.conf
2020-08-25 04:16:01,602 - INFO - attack_range - INIT - attack_range v1
2020-08-25 04:16:01,602 - INFO - attack_range - [action] > build

Traceback (most recent call last):
  File "attack_range.py", line 117, in <module>
    controller.build()
  File "/home/n7/projects/attack_range/modules/TerraformController.py", line 26, in build
    return_code, stdout, stderr = self.terraform.apply(capture_output='yes', skip_plan=True, no_color=IsNotFlagged)
  File "/home/n7/projects/attack_range/venv/lib/python3.6/site-packages/python_terraform/__init__.py", line 113, in apply
    return self.cmd('apply', *args, **option_dict)
  File "/home/n7/projects/attack_range/venv/lib/python3.6/site-packages/python_terraform/__init__.py", line 293, in cmd
    cwd=working_folder, env=environ_vars)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError:` [Errno 2] No such file or directory: 'terraform': 'terraform'
```

I tried with path variations and stuff, but nothing helped, neither could find a solution in terraform's repository. May it be related with the refactoring?

**Comment by P4T12ICK** [comment]
Did you follow the guide in here?
https://github.com/splunk/attack_range/wiki/Ubuntu-18.04-Installation

**Comment by fierytermite** [comment]
> Did you follow the guide in here?
> https://github.com/splunk/attack_range/wiki/Ubuntu-18.04-Installation

Oh, my bad, I was actually tying with this one ---> https://medium.com/@julian.wieg/splunk-attack-range-in-a-virtualized-ubuntu-guest-vm-guide-c6587f43c15 to set it up locally, since I wanted to give it a try, I notice it was a little bit outdated, but not that much 😅
