### ISSUE TITLE
Terraform build fails to get instance from AWS

### ISSUE THREAD

**Issue by harveybob** [splunk/attack_range#364]
After terraform build to AWS. 
List of instances fails post build in attack_range.put / TerraformController.py

Apply complete! Resources: 11 added, 0 changed, 0 destroyed.
2020-09-14 15:47:51,458 - INFO - attack_range - attack_range has been built using terraform successfully
Traceback (most recent call last):
  File "attack_range.py", line 146, in <module>
    main(sys.argv[1:])
  File "attack_range.py", line 124, in main
    controller.build()
  File "/Users/a565230/attack_range/modules/TerraformController.py", line 33, in build
    self.list_machines()
  File "/Users/a565230/attack_range/modules/TerraformController.py", line 170, in list_machines
    instances = aws_service.get_all_instances(self.config)
  File "/Users/a565230/attack_range/modules/aws_service.py", line 38, in get_all_instances
    if len(instance['Tags']) > 0:
KeyError: 'Tags'

**Comment by harveybob** [comment]
Running following command also fails
python attack_range.py -lm           

starting program loaded for B1 battle droid
          ||/__'`.
          |//()'-.:
          |-.||
          |o(o)
          |||\\  .==._
          |||(o)==::'
           `|T  ""
            ()
            |\
            ||\
            ()()
            ||//
            |//
           .'=`=.
    
attack_range is using config at path attack_range.conf
WARNING - with configuration file at: attack_range.conf, the attack range will be public and open to the world, it is recommended that users secure attack_range servers by whitelisting only the public IP address in this format: ip_whitelist= <X.X.X.X>/32
2020-09-14 15:54:11,078 - INFO - attack_range - INIT - attack_range v1
Traceback (most recent call last):
  File "attack_range.py", line 146, in <module>
    main(sys.argv[1:])
  File "attack_range.py", line 120, in main
    controller.list_machines()
  File "/Users/a565230/attack_range/modules/TerraformController.py", line 170, in list_machines
    instances = aws_service.get_all_instances(self.config)
  File "/Users/a565230/attack_range/modules/aws_service.py", line 38, in get_all_instances
    if len(instance['Tags']) > 0:
KeyError: 'Tags'

**Comment by P4T12ICK** [comment]
Hi, that often happens when the configured region in aws cli doesn't fit to the region specified in attack_range.conf. Can you check this?

**Comment by harveybob** [comment]
> Hi, that often happens when the configured region in aws cli doesn't fit to the region specified in attack_range.conf. Can you check this?

Thanks I have aws CLI config set to region:-
[default]
region = eu-west-2

and config "attack_range.conf" also set to:-
region = eu-west-2

**Comment by harveybob** [comment]
re-tried under a new account and worked this time.
