### ISSUE TITLE
error while building attack range

### ISSUE THREAD

**Issue by ronscorner** [splunk/attack_range#451]
i am getting following error while building attack range locally.

Traceback (most recent call last):
  File "attack_range.py", line 208, in <module>
    main(sys.argv[1:])
  File "attack_range.py", line 204, in main
    return args.func(args)
  File "attack_range.py", line 105, in build
    controller.build()
  File "/home/rivery/Desktop/attack_range/modules/TerraformController.py", line 47, in build
    return_code, stdout, stderr = self.terraform.apply(
  File "/home/rivery/Desktop/attack_range/venv/lib/python3.8/site-packages/python_terraform/__init__.py", line 113, in apply
    return self.cmd('apply', *args, **option_dict)
  File "/home/rivery/Desktop/attack_range/venv/lib/python3.8/site-packages/python_terraform/__init__.py", line 292, in cmd
    p = subprocess.Popen(cmds, stdout=stdout, stderr=stderr,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'terraform'

please help fixing this 
virtualenv --version
16.7.9
python 3.8

**Comment by patel-bhavin** [comment]
Hello, @pkamal227 : if you are building the range locally, please use this repo: https://github.com/splunk/attack_range_local and create an issue in that repo to help track better.
Thank you

**Comment by josehelps** [comment]
@pkamal227 seems base on that error that you are missing the terraform folder in your local directory. Did that get wiped out mistakenly? https://github.com/splunk/attack_range/tree/develop/terraform
