### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by askkemp** [splunk/attack_range#598]
When running the initial deployment on Ubuntu 20.04.4 LTS with `ansible-galaxy collection install community.windows` the below error occurs.

```console
(venv) user@splunk:~/attack_range_local$ ansible-galaxy collection install community.windows
Traceback (most recent call last):
  File "/home/user/attack_range_local/venv/bin/ansible-galaxy", line 62, in <module>
    import ansible.constants as C
  File "/home/user/attack_range_local/venv/lib/python3.8/site-packages/ansible/constants.py", line 12, in <module>
    from jinja2 import Template
  File "/home/user/attack_range_local/venv/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/user/attack_range_local/venv/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/user/attack_range_local/venv/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/user/attack_range_local/venv/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/user/attack_range_local/venv/lib/python3.8/site-packages/markupsafe/__init__.py)
```
I believe this is due to https://github.com/pallets/markupsafe/issues/284

The short-term fix is to add `MarkupSafe==2.0.1` into `requirements.txt`

**Comment by josehelps** [comment]
Hey thank you! We all barely use attack_range_local at this point, and mainly leverage this project for our day to day, unfortunately attack_range_local it is going unmaintained and likely will be deprecated and replaced with this project in the future. If you like to build this change as a PR against https://github.com/splunk/attack_range_local/pulls will happily approve it/merge it.
