### ISSUE TITLE
Update reqs to python3.10 and replace PyIquirer

### ISSUE THREAD

**Issue by josehelps** [splunk/attack_range#620]
most libs installed by req depend on python3.8, we should everything to latest 3.10. This causes the following error:
```
python attack_range.py build
Traceback (most recent call last):
  File "/home/ubuntu/attack_range/attack_range.py", line 5, in <module>
    from modules import configuration
  File "/home/ubuntu/attack_range/modules/configuration.py", line 9, in <module>
    from PyInquirer import prompt, Separator
  File "/home/ubuntu/attack_range/venv/lib/python3.10/site-packages/PyInquirer/__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "/home/ubuntu/attack_range/venv/lib/python3.10/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/home/ubuntu/attack_range/venv/lib/python3.10/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/home/ubuntu/attack_range/venv/lib/python3.10/site-packages/prompt_toolkit/application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "/home/ubuntu/attack_range/venv/lib/python3.10/site-packages/prompt_toolkit/key_binding/bindings/basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "/home/ubuntu/attack_range/venv/lib/python3.10/site-packages/prompt_toolkit/renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "/home/ubuntu/attack_range/venv/lib/python3.10/site-packages/prompt_toolkit/styles/__init__.py", line 8, in <module>
    from .from_dict import *
  File "/home/ubuntu/attack_range/venv/lib/python3.10/site-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by josehelps** [comment]
resolved here https://github.com/splunk/attack_range/pull/623
