### ISSUE TITLE
Ansible vars error

### ISSUE THREAD

**Issue by rosplk** [splunk/attack_range#68]
=> win10: Running provisioner: ansible...
    win10: Running ansible-playbook...
ERROR! vars file ../vars/vars.yml was not found on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
Traceback (most recent call last):
  File "attack_range.py", line 179, in <module>
    v1.up(provision=True)
  File "/Users/rsoto/attack_range/venv/lib/python3.7/site-packages/vagrant/__init__.py", line 337, in up
    self._call_vagrant_command(args)
  File "/Users/rsoto/attack_range/venv/lib/python3.7/site-packages/vagrant/__init__.py", line 963, in _call_vagrant_command
    stderr=err_fh, env=self.env)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/vagrant', 'up', '--provision']' returned non-zero exit status 1.

**Comment by P4T12ICK** [comment]
Problem is solved with the newest version of Attack Range.
