### ISSUE TITLE
Errors in configure if not using domain controller

### ISSUE THREAD

**Issue by justsean9** [splunk/attack_range#742]
If you do not select "yes" on adding server as domain controller the configure errors out.

`Traceback (most recent call last):
  File "attack_range.py", line 231, in <module>
    main(sys.argv[1:])
  File "attack_range.py", line 227, in main
    return args.func(args)
  File "attack_range.py", line 103, in configure
    configuration.new(args.config)
  File "/attack_range/modules/configuration.py", line 453, in new
    if answers['windows_server_one_bad_blood']:
KeyError: 'windows_server_one_bad_blood'`

**Comment by Egotism3851** [comment]
+1 I also had this issue

**Comment by P4T12ICK** [comment]
I will check it. Thank you for reporting it.
