### ISSUE TITLE
docker arm64 - wrong terraform package

### ISSUE THREAD

**Issue by kruj0** [splunk/attack_range#793]
The arm64 docker image downloads the wrong terraform package:
https://github.com/splunk/attack_range/blob/develop/docker/Dockerfile#L7

because of this, the framework will fail with a terraform issue.

A workaround is to overwrite the terraform package after the container is started.

A solution for the future would be, to download the right terraform packge with the right OS/Arch Flag.

**Comment by P4T12ICK** [comment]
I tested it with both an amd64 and arm MacBook and it worked. What is exactly failing for you?

**Comment by kruj0** [comment]
hi patrick,

i configured a default config with a windows maschine and nothing elese via python attack_range.py configure inside a docker container on my arm m1 macbook.
used container version: latest
here is the output on my m1 arm macbook:

```
(attack-range-py3.8) root@508f894a2288:/attack_range# python attack_range.py build
                   
                              __
                            .d$$b
                          .' TO$;\
                         /  : TP._;
                        / _.;  :Tb|
                       /   /   ;j$j
                   _.-"       d$$$$
                 .' ..       d$$$$;
                /  /P'      d$$$$P. |\
               /   "      .d$$$P' |\^"l
             .'           `T$P^"""""  :
         ._.'      _.'                ;
      `-.-".-'-' ._.       _.-"    .-"
    `.-" _____  ._              .-"
   -(.g$$$$$$$b.              .'
     ""^^T$$$P^)            .(:
       _/  -"  /.'         /:/;
    ._.'-'`-'  ")/         /;/;
 `-.-"..--""   " /         /  ;
.-" ..--""        -'          :
..--""--.-"         (\      .-(\
  ..--""              `-\(\/;`
    _.                      :
                            ;`-
                           :\
                           ;  bug

By: Splunk Threat Research Team [STRT] - research@splunk.com

    
2023-05-15 08:17:39,874 - INFO - attack_range - [action] > build

2023-05-15 08:17:39,874 - INFO - attack_range - Check if images are available in region eu-central-1
2023-05-15 08:17:40,115 - INFO - attack_range - Image splunk-v3-0-0 is available in region eu-central-1
2023-05-15 08:17:40,200 - INFO - attack_range - Image windows-2016-v3-0-0 is available in region eu-central-1
sh: 1: terraform: Exec format error
Traceback (most recent call last):
  File "attack_range.py", line 231, in <module>
    main(sys.argv[1:])
  File "attack_range.py", line 227, in main
    return args.func(args)
  File "attack_range.py", line 84, in build
    controller.build()
  File "/attack_range/modules/aws_controller.py", line 90, in build
    return_code, stdout, stderr = self.terraform.apply(
  File "/root/.cache/pypoetry/virtualenvs/attack-range-536x2-W_-py3.8/lib/python3.8/site-packages/python_terraform/__init__.py", line 113, in apply
    return self.cmd('apply', *args, **option_dict)
  File "/root/.cache/pypoetry/virtualenvs/attack-range-536x2-W_-py3.8/lib/python3.8/site-packages/python_terraform/__init__.py", line 292, in cmd
    p = subprocess.Popen(cmds, stdout=stdout, stderr=stderr,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'terraform'

```
here the version output from terraform:
```
(attack-range-py3.8) root@508f894a2288:/attack_range# terraform --version
bash: /usr/local/bin/terraform: cannot execute binary file: Exec format error
```
used kernel information:
```
(attack-range-py3.8) root@508f894a2288:/attack_range# uname -ar
Linux 508f894a2288 5.15.0-1034-oracle #40-Ubuntu SMP Wed Apr 19 16:10:04 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

here is my workaround, where i used the arm64 binaries from terraform:
```
wget https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_arm64.zip
unzip terraform_1.4.6_linux_arm64.zip 
mv terraform /usr/local/bin/terraform 
```
with this arm64 binaries it will build a attack scenario.
The problem occours on my arm64 macos and also in the aws where i use a t4g.micro instance as an bastion host (arm64).

**Comment by P4T12ICK** [comment]
I will have a look into this. Thank you for reporting.

**Comment by P4T12ICK** [comment]
I don't run into the same issue with my M1 MacBook.

**Comment by kruj0** [comment]
then lets close this issue. as i said. i have an workaround and if you dont run into the same problem, dann its may already fixed.
thanks for your time.
