### ISSUE TITLE
attack_range.py build fails on ubuntu 23.04

### ISSUE THREAD

**Issue by blvrkr** [splunk/attack_range#838]
Attack_range.py build local deployment fails on Ubuntu 23.04. Tried with python 3.11 and 3.10.

```
(attack-range-py3.10) user@ubuntu:~/Downloads/attack_range$ python attack_range.py build
                   
                              __
                            .d$$b
                          .' TO$;\
                         /  : TP._;
                        / _.;  :Tb|
                       /   /   ;j$j
                   _.-"       d$$$$
                 .' ..       d$$$$;
                /  /P'      d$$$$P. |\
               /   "      .d$$$P' |\^"l
             .'           `T$P^"""""  :
         ._.'      _.'                ;
      `-.-".-'-' ._.       _.-"    .-"
    `.-" _____  ._              .-"
   -(.g$$$$$$$b.              .'
     ""^^T$$$P^)            .(:
       _/  -"  /.'         /:/;
    ._.'-'`-'  ")/         /;/;
 `-.-"..--""   " /         /  ;
.-" ..--""        -'          :
..--""--.-"         (\      .-(\
  ..--""              `-\(\/;`
    _.                      :
                            ;`-
                           :\
                           ;  bug

By: Splunk Threat Research Team [STRT] - research@splunk.com

    
Traceback (most recent call last):
  File "/home/user/Downloads/attack_range/attack_range.py", line 231, in <module>
    main(sys.argv[1:])
  File "/home/user/Downloads/attack_range/attack_range.py", line 227, in main
    return args.func(args)
  File "/home/user/Downloads/attack_range/attack_range.py", line 83, in build
    controller = init(args)
  File "/home/user/Downloads/attack_range/attack_range.py", line 50, in init
    config = ConfigHandler.read_config(config_path)
  File "/home/user/Downloads/attack_range/modules/config_handler.py", line 20, in read_config
    yml_dict_default[parent_key][key] = yml_dict[parent_key][key]
TypeError: list indices must be integers or slices, not dict
(attack-range-py3.10) user@ubuntu:~/Downloads/attack_range$ python -V
Python 3.10.4

```
It works fine on Ubuntu 22.04 LTS with python 3.10.6.
Maybe documentation could include some hints regarding what distros is AR confirmed to work with.

**Comment by blvrkr** [comment]
This seems to be some config issue. Closing for now and will re-open when double-checked.
