### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by akilbekov** [splunk/attack_range#94]
OS: Fedora 31 5.3.11-300.fc31.x86_64
Vagrant: 2.2.6
VirtualBox: 6.0.14

Followed vagrant/virtualbox configuration page and then tried to build: 

```
python attack_range.py -m vagrant -a build

starting program loaded for B1 battle droid
          ||/__'`.
          |//()'-.:
          |-.||
          |o(o)
          |||\\  .==._
          |||(o)==::'
           `|T  ""
            ()
            |\
            ||\
            ()()
            ||//
            |//
           .'=`=.
    
attack_range is using config at path attack_range.conf
2019-11-26 15:49:22,301 - INFO - attack_range - INIT - attack_range v1
2019-11-26 15:49:22,301 - INFO - attack_range - INIT - Attack Range v1
2019-11-26 15:49:22,303 - INFO - attack_range - [mode] > vagrant
2019-11-26 15:49:22,303 - INFO - attack_range - building splunk-server and windows10 workstation boxes WARNING MAKE SURE YOU HAVE 8GB OF RAM free otherwise you will have a bad time
2019-11-26 15:49:22,304 - INFO - attack_range - [action] > build

Bringing machine 'splunk-server' up with 'virtualbox' provider...
Bringing machine 'win10' up with 'virtualbox' provider...
==> splunk-server: Checking if box 'generic/ubuntu1804' version '2.0.4' is up to date...
==> splunk-server: Running provisioner: ansible...
    splunk-server: Running ansible-playbook...

...........

PLAY RECAP *********************************************************************
splunk-server              : ok=17   changed=0    unreachable=0    failed=0   

==> win10: Checking if box 'd1vious/windows10' version '1.0' is up to date...
Traceback (most recent call last):
  File "attack_range.py", line 452, in <module>
    vagrant_mode(action, log)
  File "attack_range.py", line 163, in vagrant_mode
    v1.up(provision=True)
  File "/home/dauren/projects/attack_range/venv/lib/python3.7/site-packages/vagrant/__init__.py", line 337, in up
    self._call_vagrant_command(args)
  File "/home/dauren/projects/attack_range/venv/lib/python3.7/site-packages/vagrant/__init__.py", line 963, in _call_vagrant_command
    stderr=err_fh, env=self.env)
  File "/usr/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/vagrant', 'up', '--provision']' returned non-zero exit status 1.


```
After downloading the windows box it fails.

**Comment by P4T12ICK** [comment]
@akilbekov I will check it and come back to you today.

**Comment by P4T12ICK** [comment]
@akilbekov 
For me the current develop branch is working. Can you please do the following:
1) remove the not completed build VMs in Virtualbox
2) run: `cd vagrant && vagrant up`
3) share the error message in this thread.
Thank you very much.

**Comment by akilbekov** [comment]
```
A VirtualBox machine with the name 'win10' already exists.
Please use another name or delete the machine with the existing
name, and try again.

```
OK, so the problem was, that I already had machine with the name 'win10' from other experiments. After renaming, everything works.
